{% set name = "lastpass-cli" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lastpass/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e4ff5c9fef8aa924547c565c44e5b4aa31e63d642873847b8e40ce34558a5e1

build:
  number: 1
  script: "make && make install"
  # Skip windows build, but upstream supports windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - asciidoc  # [not win]
    - libxml2   # [not win]
    - cmake
    - make
    - pkg-config
  host:
    - libcurl
    - libxml2
    - openssl

test:
  commands:
    - lpass -v

about:
  home: https://www.lastpass.com
  license: GPL-2.0-or-later
  license_file:
    - LICENSE.OpenSSL
    - COPYING
  summary: 'LastPass command line interface tool'
  doc_url: https://lastpass.github.io/lastpass-cli/lpass.1.html
  dev_url: https://github.com/lastpass/lastpass-cli

extra:
  recipe-maintainers:
    - asford
    - danielnachun
    - tdsmith
