{% set name = "lastpass-cli" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lastpass/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e317c7ac964e35d8535e039b70c0eab26fe4ef5aa596ad0f09f72fd8c7207d87
  patches:
    # Need patch from https://github.com/lastpass/lastpass-cli/issues/532
    - 532-fix-common.patch

build:
  number: 0
  script: "make && make install"
  # Skip windows build, but upstream supports windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - asciidoc  # [not win]
    - libxml2   # [not win]
    - cmake
    - make
    - pkg-config
  host:
    - libcurl
    - libxml2
    - openssl

test:
  commands:
    - lpass -v

about:
  home: https://www.lastpass.com
  license: GPL-2.0-or-later
  license_file:
    - LICENSE.OpenSSL
    - COPYING
  summary: 'LastPass command line interface tool'
  doc_url: https://lastpass.github.io/lastpass-cli/lpass.1.html
  dev_url: https://github.com/lastpass/lastpass-cli

extra:
  recipe-maintainers:
    - asford
