{% set name = "lastpass-cli" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lastpass/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 542dc3d7ff175866c0eddfcc6f2dffdb54acf6854dd1fadaf4d509dcde2d4bf3

build:
  number: 2
  string: libxml211
  script: "make && make install"
  # Skip windows build, but upstream supports windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - asciidoc  # [not win]
    - libxml2 ~=2.11.5   # [not win]
    - cmake
    - make
    - pkg-config
  host:
    - libcurl
    - libxml2 ~=2.11.5
    - openssl
  run:
    - libxml2 ~=2.11

test:
  commands:
    - lpass -v

about:
  home: https://www.lastpass.com
  license: GPL-2.0-or-later
  license_file:
    - LICENSE.OpenSSL
    - COPYING
  summary: 'LastPass command line interface tool'
  doc_url: https://lastpass.github.io/lastpass-cli/lpass.1.html
  dev_url: https://github.com/lastpass/lastpass-cli

extra:
  recipe-maintainers:
    - asford
    - tdsmith
