{% set name = "lastpass-cli" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lastpass/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d52616fc1065eb7122cd9b43a31c4155eed22c3ef9d2806dbb3cb49e9d38859

build:
  number: 0
  script: "make && make install"
  # Skip windows build, but upstream supports windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - asciidoc  # [not win]
    - libxml2   # [not win]
    - cmake
    - make
    - pkg-config
  host:
    - libcurl
    - libxml2
    - openssl

test:
  commands:
    - lpass -v

about:
  home: https://www.lastpass.com
  license: GPL-2.0-or-later
  license_file:
    - LICENSE.OpenSSL
    - COPYING
  summary: 'LastPass command line interface tool'
  doc_url: https://lastpass.github.io/lastpass-cli/lpass.1.html
  dev_url: https://github.com/lastpass/lastpass-cli

extra:
  recipe-maintainers:
    - asford
    - tdsmith
